apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: old-ermine-java-springboot 
  janus-idp.io/tekton: old-ermine-java-springboot
  backstage.io/kubernetes-id: old-ermine-java-springboot
  backstage.io/kubernetes-namespace: rhtap-e2e 
  app.kubernetes.io/part-of: old-ermine-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  